Added Bubble Sort In Kotlin
amanmehara/programming pull request #146
Opened 2020-10-12 05:28 UTC by gajendrapandeya

Hey there, 
I have added bubble sort in kotlin

2020-10-16 05:28 UTC, amanmehara requested changes
Please remove other extra files committed.

Also have a look at [CONTRIBUTING.md](https://github.com/amanmehara/programming/blob/master/CONTRIBUTING.md) and make changes accordingly.
I'll approve and merge afterwards! 😃

2020-10-16 05:28 UTC, amanmehara commented on Kotlin/src/Sorting/BubbleSort.kt
> +package Sorting
Add the license header here.

2020-10-16 05:31 UTC, gajendrapandeya commented
I am new to open source
What things I need to exclude ??

On Fri, 16 Oct 2020, 11:13 Aman Mehara, <notifications@github.com> wrote:

> *@amanmehara* requested changes on this pull request.
>
> Please remove other extra files committed.
>
> Also have a look at CONTRIBUTING.md
> <https://github.com/amanmehara/programming/blob/master/CONTRIBUTING.md>
> and make changes accordingly.
> I'll approve and merge afterwards! 😃
> ------------------------------
>
> In Kotlin/src/Sorting/BubbleSort.kt
> <https://github.com/amanmehara/programming/pull/146#discussion_r506059920>
> :
>
> > @@ -0,0 +1,27 @@
>
> +package Sorting
>
>
> Add the license header here.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/amanmehara/programming/pull/146#pullrequestreview-510118281>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AM53KUJM3IQAV2WKYWA63BLSK7KYVANCNFSM4SMKGV4A>
> .
>

2020-10-16 05:33 UTC, amanmehara commented
@gajendrapandeya Only `Kotlin/src/Sorting/BubbleSort.kt` file is required.

All other files are IDE project specific files.

2020-10-16 05:38 UTC, gajendrapandeya commented
Kotlin runtime environment is required to run the kotlin program
So shall I exclude that as well ?

On Fri, 16 Oct 2020, 11:19 Aman Mehara, <notifications@github.com> wrote:

> @gajendrapandeya <https://github.com/gajendrapandeya> Only
> Kotlin/src/Sorting/BubbleSort.kt file is required.
>
> All other files are IDE project specific files.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/amanmehara/programming/pull/146#issuecomment-709800460>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AM53KUIDEQD4EMUYQQGS7J3SK7LMRANCNFSM4SMKGV4A>
> .
>

2020-10-16 05:41 UTC, amanmehara commented
Yes, exclude them also for now.
I'll later on find a way to build these Kotlin source files and have test cases, then we might add them back.

2020-10-16 05:45 UTC, gajendrapandeya commented
Okay sure thanks 😊

On Fri, 16 Oct 2020, 11:26 Aman Mehara, <notifications@github.com> wrote:

> Yes, exclude them also for now.
> I'll later on find a way to build these Kotlin source files and have test
> cases, then we might add them back.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/amanmehara/programming/pull/146#issuecomment-709804811>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AM53KUMXCOOL2YIPTAKV3ULSK7MI3ANCNFSM4SMKGV4A>
> .
>

2020-10-16 06:48 UTC, gajendrapandeya commented
Hello how could i exclude those files. I have googled but still can't figure out

2020-11-01 04:59 UTC, amanmehara commented
Closing as there are no updates here for more than 2 weeks.

2020-11-01 04:59 UTC, closed without merging